### ISSUE TITLE
ReplyError: ERR wrong number of arguments for 'ft.create' command

### ISSUE THREAD

**Issue by waleedarshad-vf** [stockholmux/node_redis-redisearch#10]
client = redis.createClient({
    host: redisEndpoint,
    connect_timeout: 5000
  });
  redisearch(redis);

 client.ft_create("myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT")

**Comment by stockholmux** [comment]
Split up arguments. 
Something like: `client.ft_create("myIdx", "SCHEMA", "title", "TEXT", ...`

**Comment by waleedarshad-vf** [comment]
Thanks.
