### ISSUE TITLE
Info command returning only true

### ISSUE THREAD

**Issue by waleedarshad-vf** [stockholmux/node_redis-redisearch#11]
client = redis.createClient({
host: redisEndpoint,
connect_timeout: 5000
});
redisearch(redis);

client.ft_create("userIndex SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT")
client.ft_info('userIndex') // **it return true only**

if from redis-cli 
we do 
**FT.INFO userIndex** 
it gives

    `   1) index_name
     2) userIndex
     3) index_options
     4) (empty list or set)
     5) fields
     6) 1) 1) _id
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
    2) 1) firstName
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
    3) 1) lastName
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
    4) 1) username
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
    5) 1) profilePicture
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
    6) 1) verified
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
      7) num_docs
     8) "2"
     9) max_doc_id
    10) "2"
    11) num_terms
    12) "12"
    13) num_records
     14) "15"
     15) inverted_sz_mb
     16) "8.7738037109375e-05"
     17) total_inverted_index_blocks
     18) "12"
        ......
        ......
        ......
`

**Comment by stockholmux** [comment]
You need a callback or to implement promises for `async` /  `await` (see [util.promisify](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original))

Callback example:
```
client.ft_info('userIndex', (err,result) => { console.log(result); })
```

**Comment by waleedarshad-vf** [comment]
How can i read for the documentation. is it written somwhere?. I was trying with .then syntax but failed. Can you refer me the source code from where you are reading these methods syntax and details?

Thanks for quick response. Appreciate it :)

**Comment by stockholmux** [comment]
@waleedarshad-vf Take a look at the [node_redis section on promises](https://github.com/NodeRedis/node-redis#promises) To make it `async` / `await` then you'd need to do the normal wrapping of of the commands in an `async` function.

Alternately, you can use another module I created, [async_node_redis](https://github.com/stockholmux/async_node_redis) that wraps node_redis so it will be all async. I just added an [example for module commands](https://github.com/stockholmux/async_node_redis/blob/master/example/module.js) - in place of the `addCommand` line in this example, use something like `redisearch(asyncNodeRedis)`
